// <auto-generated />
using System;
using Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DummyDbContext))]
    partial class DummyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Domain.Models.Entities.Dummy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dummy");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d492016-8364-430c-8cd2-979a00990f0b"),
                            Name = "6d4920168364430c8cd2979a00990f0b"
                        },
                        new
                        {
                            Id = new Guid("b380079b-2e50-45ad-976a-1639add85b52"),
                            Name = "b380079b2e5045ad976a1639add85b52"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
